Add additional filter variables
Can now use the following in filter expressions:

error: the error string or ""
down/up: the download/upload rate in KB/sec
age: the age (since doneDate or addedDate) in seconds
downloadDir: the download directory
priority: the priority (low, normal, high)
name: the torrent name
status: the status (e.g stopped) or ""